[package]
name = "advent_of_code_2024"
version = "0.1.0"
authors = ["Pieter Frenssen <pieter@frenssen.be>"]
edition = "2021"

[dependencies]
aoc-runner = "^0.3.0"
aoc-runner-derive = "^0.3.0"
indoc = "^2.0.5"
regex = "^1.11.1"
strum = "0.26.3"
strum_macros = "0.26.4"
